version: '3.8'

services:
  jenkins:
    container_name: jenkins
    restart: unless-stopped
    build:
      dockerfile: Dockerfile.w

    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh/known_hosts:/var/jenkins_home/.ssh/known_hosts:ro

volumes:
  jenkins_home:
