version: '3.8'

services:
  mongo1:
    image: mongo:6.0
    container_name: mongo1
    ports:
      - "27017:27017"
    command: [ "--replSet", "optiroute" ]
    volumes:
      - mongo1-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - mongo-net

  mongo2:
    image: mongo:6.0
    container_name: mongo2
    ports:
      - "27018:27017"
    command: [ "--replSet", "optiroute" ]
    volumes:
      - mongo2-data:/data/db
    networks:
      - mongo-net

  mongo3:
    image: mongo:6.0
    container_name: mongo3
    ports:
      - "27019:27017"
    command: [ "--replSet", "optiroute" ]
    volumes:
      - mongo3-data:/data/db
    networks:
      - mongo-net

  nest-app:
    build:
      context: .
    container_name: nest-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo1
      - mongo2
      - mongo3

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - mongo-net
networks:
  mongo-net:
    driver: bridge

volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data:
